development:
  adapter: postgresql
  encoding: unicode
  database: alotto
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: alotto
  pool: 5
  host: <%= ENV['HEROKU_POSTGRESQL_YELLOW_URL'] %>
